### ISSUE TITLE
Support "Token Action HUD" module

### ISSUE THREAD

**Issue by samuelboland** [SobranDM/foundryvtt-wwn#15]
[Token Action Hud](https://foundryvtt.com/packages/token-action-hud/) is useful module that allows users to perform actions without opening the character sheet. In 5E, SW5E, and PF2E, it supports things like Items, Magic, Saving Throws, and Skill checks. For GMs, it allows toggling token visibility and status effects. 

It would be nice to have support for this in WWN. 

Thanks!

**Comment by SobranDM** [comment]
This looks very useful. I'll look into it, likely after the release of Foundry v10. That is going to involve some data restructuring, so it'll be easier to support that module after the new structure shakes out.

**Comment by SobranDM** [comment]
Supported as of 1.4.0
