### ISSUE TITLE
Psychic skills not showing even after option checked

### ISSUE THREAD

**Issue by mascarenhas** [SobranDM/foundryvtt-wwn#16]
Using version 0.9.9c of the character sheet in Foundry v9 (hosted in the forge), I went to the "System Settings" tab of the "Configure Settings" dialog and checked the "Psychic Skills" checkbox but those skills are still now showing, even in newly-created actors. Please let me know if you need anything else that would help, and thanks a lot for all the work in this!

**Comment by mascarenhas** [comment]
Take a look at PR #17, I would assume the problem was a change to how Foundry uses the templates.

**Comment by SobranDM** [comment]
Solved in v1.0.0
