### ISSUE TITLE
Heal button next to apply damage 

### ISSUE THREAD

**Issue by wintersleepAI** [SobranDM/foundryvtt-wwn#21]
This is more a suggestion than a bug, but it could be good to add a heal button next to the damage buttons on attack rolls. Sometimes folks apply damage to the wrong actor, this allows an easy way to undo. I believe this is in the 5e system (along with 1/2  and 1/4 damage). Alternatively this could be done with a context for apply healing by (right) clicking on the window -- although the presence of shock damage makes this harder)

**Comment by SobranDM** [comment]
Good idea. I'll try to get this in with the next update.

**Comment by SobranDM** [comment]
Added right-click options to heal based on the damage roll or shock.
