### ISSUE TITLE
New Actors Making Foundry Unresponsive

### ISSUE THREAD

**Issue by DarkBearmancula** [SobranDM/foundryvtt-wwn#27]
Foundry becomes unresponsive when attempting to create a new actor. I found another repot of this issue in Foundry's Discord, but see no record of it here. If I close Foundry and re-open it, the new actor I was attempting to create is not present. 

System version v1.0.0

Foundry is updated to Version 10 - Build 287, this was also happening on previous V10 builds as well.

https://user-images.githubusercontent.com/73794994/194684293-b0596f85-a00b-438d-bad4-debd5060b53e.mp4

**Comment by Cup-of-Coffee** [comment]
A snippet of the console when attempting to create a new Actor.

![Screenshot 2022-10-12 162021](https://user-images.githubusercontent.com/39238717/195440395-973cfe9f-67ae-4fdd-b39e-031f211bb5a6.png)

**Comment by sdsalyer** [comment]
I suppose this explains why the bestiary compendium won't load as well. This renders the game system unusable.

**Comment by SobranDM** [comment]
fixed in upcoming update
