### ISSUE TITLE
v10 Migration Support

### ISSUE THREAD

**Issue by Cup-of-Coffee** [SobranDM/foundryvtt-wwn#28]
Migrating the system to v10.

**Comment by mclemente** [comment]
Hello, I just noticed your settings still use `onChange: _ => window.location.reload()` and V10 uses `requiresReload: true` instead. This change avoids settings not being saved when users change multiple settings that reload.

**Comment by Cup-of-Coffee** [comment]
Thanks for the help! I added the changes to the latest Pull request.
