### ISSUE TITLE
Feature Suggestion: Adding Health Modifier

### ISSUE THREAD

**Issue by Cup-of-Coffee** [SobranDM/foundryvtt-wwn#32]
A suggestion to add a modifier to overall hit points by a specific amount that isn't increased by level, placed in <Tweaks>. This can be used for Heroic characters, gaining 12 additional hit points at level 1.

**Comment by Cup-of-Coffee** [comment]
This may be redundant when foundry's Active Effects is fully implemented.

**Comment by SobranDM** [comment]
Should be able to do this with Active Effects now.
