### ISSUE TITLE
Duplicating Character Actors results in extra Skills

### ISSUE THREAD

**Issue by TheBiggerBadderWolf** [SobranDM/foundryvtt-wwn#36]
Foundry Version: 9 (Build 269)
WWN Version: 1.0.0

If this is the same as issue 5 in #30 please close.

When duplicating a (player) Character Actor, the duplicated Actor has each skill displayed twice (and three times if a duplicate is duplicated etc.)

To reproduce:
1) Create an Actor of type 'Character'
2) Right-click this Actor and click 'Duplicate'
3) Open the new duplicated actor and note the Skill Box

Observed Result: Each Skill is displayed twice
Expected Result: Each Skill is displayed just once, even when an Actor is duplicated.

![actor_dupe](https://user-images.githubusercontent.com/76487459/196967597-9725f437-66af-4d0b-8d28-7775328f3838.jpg)

**Comment by SobranDM** [comment]
Fixed in next patch

**Comment by Cup-of-Coffee** [comment]
This appears to be resolved as of the 1.01 beta.
