### ISSUE TITLE
 Feature Suggestion: Elixir Encumberance

### ISSUE THREAD

**Issue by Cup-of-Coffee** [SobranDM/foundryvtt-wwn#42]
Elixirs have a special interaction with encumbrance, and the sheet currently doesn't support it.

> Given the careful packing usually required to keep an elixir from becoming damaged in transit, each one counts as one item of encumbrance when Readied. The GM may allow any reasonable number of these little vials to be cased or wrapped together in a pack without encumbrance costs, but digging these stored ones out individually takes too long to be practical in combat.

**Comment by SobranDM** [comment]
Added in 1.0.1-beta6
