### ISSUE TITLE
Crashing upon creating new Actor

### ISSUE THREAD

**Issue by Gobbis** [SobranDM/foundryvtt-wwn#50]
Just got the module and set up a game world within Foundry, but the world crashes immediately if I try to create a new actor.

**Comment by Gobbis** [comment]
I have tried a number of ways to ensure the error isn't on my end - my Foundry works fine in my other campaigns, creating Actors there is not a problem. I have reinstalled the system and made new worlds. No luck so far. Creating Items works fine.

**Comment by Cup-of-Coffee** [comment]
What is your current foundry version and what link did you use to install foundry?

**Comment by Gobbis** [comment]
I just installed it through the usual interface and assumed it would work, my bad. Works great now, thanks!
