### ISSUE TITLE
Items no longer rolling when changed

### ISSUE THREAD

**Issue by Clown-Cuddles** [SobranDM/foundryvtt-wwn#62]
Customized weapons no longer rolled, even if changes were reverted. Opening the edit sheet at all will break them, even without making any changes.

**Comment by SobranDM** [comment]
It appears the migration didn't correctly update skills. For affected actors, edit their Stab, Shoot, and Punch skills and ensure they are set as combat skills.

**Comment by Clown-Cuddles** [comment]
That seemed to fix it, thank you much
