### ISSUE TITLE
Some actors from actors compendium don't import

### ISSUE THREAD

**Issue by JhaelenTerear** [SobranDM/foundryvtt-wwn#63]
Hello,

When I try to import (bulk or one by one) the actors from the compendium provided, I have an error notification about being impossible to import null value something for multiple ones.

I'll update this report in the afternoon when I'll be back in front of my computer.

**Comment by SobranDM** [comment]
When you upgraded to Foundry v10, you may have done it within the app. v10 got some new dependencies that require a new install. If you haven't already, download Foundry v10 and install it right on top of your existing installation. If that doesn't work, get back to me.
