### ISSUE TITLE
Spellcaster option not appearing in the tweaks tab?

### ISSUE THREAD

**Issue by Darkcell28** [SobranDM/foundryvtt-wwn#68]
![Screenshot 2023-06-18 212244](https://github.com/SobranDM/foundryvtt-wwn/assets/137020318/1baa8447-2fae-4f85-94a8-c0a0e6256519)
The description for the system says that there should be an option to open the spellcasting tab on the tweaks screen for characters, but there isn't one. Am I looking in the wrong place?

**Comment by SobranDM** [comment]
I changed the system but it's a bit unintuitive. I need to switch it to support both methods. In short:

Drag an Art and/or Spell onto the sheet and the appropriate section will appear.
