### ISSUE TITLE
Packaging system-agnostic tables/tags as their own module

### ISSUE THREAD

**Issue by rsek** [SobranDM/foundryvtt-wwn#74]
Hi there,

WWN's system-agnostic tables are frequently used with other TTRPGs. I'm interested in packaging them as their own module, so that anyone can pull them in to the FVTT setup.

1) Do I have your blessing to use `foundryvtt-wwn`'s data as a base for this? License or no, I figure it's polite to ask. :) Of course I'll include credit and a link to this system package in the module description.
2) Which tables still need data entry done, if any?
3) Is this something you'd be interested in using a dependency?

### Why a dependency?

Well, there's some enhancements I'd like to make:
* adding any missing tables
* organizing tables into (vanilla FVTT) folders
* assigning an icon to each table/tag
* adding a page-number-based value to  `RollTable#sort`, so that a manual sort mode displays them in (roughly) the same order as the book does
* organizing tables into a single pack (to make it easier to search)
  * I can provide migration script to update document link UUIDs in user documents
* for tag `JournalEntry`s, reformatting the HTML content into multiple `JournalEntryPage`s. This would largely be for semantic/accessibility/clarity reasons (the book uses single letter abbreviations, but we don't have the same space constraints in FVTT, so I reckon we can do better). But it has a potential fringe benefit: encapsulating tag elements (enemies, things, etc) as embedded `JournalEntryPage`s, which makes them more accessible to programmatic use

Those may be desirable to `foundryvtt-wwn`. I'd be happy to give you commit access to the future repo if you're interested in pursuing that. If not, fair enough -- the source will be online if you'd like to adopt some or all of the changes, too.

**Comment by SobranDM** [comment]
Go for it! If you install WWN on Foundry v10 as opposed to v11, you have
easier access to the data, though you can still get at it in v11 through
the CLI if you know your way around that.

**Comment by SobranDM** [comment]
Quick follow-up:

There may be a table here or there that hasn't been done but the vast
majority have. If you were to look for what's missing, I'd start in the
religion / political section. I also haven't done monster tables, to my
recollection.

All master tables should already be in one pack but the sub-tables are in a
separate pack to avoid confusion. This is for things like the individual
tables on the One Roll tables, for example, which one rarely rolls alone.
They could be organized significantly differently now that compendiums
support folders natively, however.

**Comment by rsek** [comment]
> There may be a table here or there that hasn't been done but the vast majority have. If you were to look for what's missing, I'd start in the religion / political section. I also haven't done monster tables, to my recollection.

Cool, I'll take a look. Thanks!

> All master tables should already be in one pack but the sub-tables are in a
separate pack to avoid confusion. This is for things like the individual
tables on the One Roll tables, for example, which one rarely rolls alone.
They could be organized significantly differently now that compendiums
support folders natively, however.

Right, makes sense. My plan is to keep the master tables in the top level of compendium, with the subtables occupying nested folders (using the header hierarchy of the book as a guide). We'll see how that bears out, but between the folders and search filter available in v11+, I'm feeling optimistic. :)
