### ISSUE TITLE
Can't add "Assets" to factions.

### ISSUE THREAD

**Issue by JosheGreeneberge** [SobranDM/foundryvtt-wwn#75]
Hey, appreciate the module. On the most recent version of Foundry, I don't appear to be able to add "Assets" as inventory to a faction.

![Screenshot 2023-11-17 174147](https://github.com/SobranDM/foundryvtt-wwn/assets/58874268/9eb8e295-357a-416d-a7e2-8955edb94040)

**Comment by orkaboy** [comment]
I also see the same issue, running V11 Build 315.

**Comment by SobranDM** [comment]
Fixed in 1.3.0
