### ISSUE TITLE
State of system and V12 support

### ISSUE THREAD

**Issue by varys1337** [SobranDM/foundryvtt-wwn#82]
First of all, I would like to express my gratitude for the wonderful work you have done on the system. Considering that this is a side project, which is non-profit and freely distributed, the effort and quality are truly commendable. While the system is comprehensive and meets the needs of an everyday-gm, I have a few questions regarding its development and future enhancements.

1) **V12 Support**: Is there a plan for V12 support? Back in version 1.2.0 changelog , you mentioned working on another system related to WwN. Is this new system nearing release in the foreseeable future? Additionally, is there an intention to port the current OSE-based system to V12?

2) **Vehicles Sheet Update**: Are there any updates on the Vehicles Sheet (https://github.com/SobranDM/foundryvtt-wwn/issues/5)? Is it possible to base these sheets on wintersleep-ai's sheets or anyhow borrow it from that system for helping you in creation of such?

3) **Token HUD Support**: Is there any possibility of adding token HUD support (https://github.com/SobranDM/foundryvtt-wwn/issues/15)? Currently, there is a released token HUD for OSE-compatible systems (https://github.com/Larkinabout/fvtt-token-action-hud-core).

4) **Active Effects and Actor Data**: After the release of the version that supports Active Effects, I couldn't find any data related to the skill section. For characters, skills were typically associated with "skillNames[0]" which vary actor to actor . Is there a way to access skill values for active effects?

5) **Inline Rolling Support**: Is there any chance to see inline rolling support? While full automation support might not be feasible at the moment, the ability to perform inline rolls would be a significant first step towards it. Any other form of quick wiki where you would share knowledge how to work with the system macro writing would be very appreciated too.

**Comment by SobranDM** [comment]
1) v12 supported as of 1.4.0
2) Nothing just yet, but I do plan on adding at least a basic sheet for carts and the like. Support for ships from the Atlas are unlikely in this package. A replacement for this system is in the works. I will attempt to support it there, but have no time frame.
3) Token HUD support added in 1.4.0
4) You can add skills to _some_ things with `@convince` and the like. Unfortunately, active effects doesn't support referencing actor properties when calculating how to modify some other thing. At least not out of the box. That's something I'll be looking to support in the next system.
5) Unclear what is meant by inline rolling in this context. Can you elaborate?

**Comment by varys1337** [comment]
Thank you again for the work, response and the update!

3. I suppose as soon as OSE based token HUD (https://foundryvtt.com/packages/token-action-hud-ose) gets updated for v12 then it will be supported as well for WwN here ? Because currently Token HUD Core (https://github.com/Larkinabout/fvtt-token-action-hud-core) support is not doing anything for the user/gm apart from being validated in the module list.
5.  Something aking to PF2E styles (https://github.com/foundryvtt/pf2e/wiki/Style-Guide) or DnD 5e enrichers (https://github.com/foundryvtt/dnd5e/wiki/Enrichers)

**Comment by SobranDM** [comment]
3) I haven't gotten it added to Foundry's package list yet. Install from this link for now: https://github.com/SobranDM/token-action-hud-wwn/releases/download/1.0.1/module.json

Re: 5... Due to the complexity, that's unlikely to see implementation here, but it's worth looking at for the next system. At the moment, abilities, spells, and the like tend to implement saves through a hardcoded dropdown. The enricher looks like it could replace several other systems. Something to keep in mind for the next system.

**Comment by varys1337** [comment]
Many thanks once again!
