### ISSUE TITLE
Compendium Import/Export is broken in v12

### ISSUE THREAD

**Issue by tuirgin** [SobranDM/foundryvtt-wwn#84]
- Foundry 12.327
- WWN 1.4.2

Importing compendiums results in a folder being created with a matching number of items from the original compendium, however each item is a duplicate of a single item. 
- Importing "Armor" results in 18 copies of "Impervious Defense".
    ![image](https://github.com/SobranDM/foundryvtt-wwn/assets/97160/9781891c-8df0-45bd-a3d6-d723b9f1b197)
- The Foundry logs show the typical "Created Item with id [...]" entries with each item having a unique id.
    ![image](https://github.com/SobranDM/foundryvtt-wwn/assets/97160/b62b1b62-19fb-4957-8437-9e3be08d3b69)

Exporting folders to compendium results in folder hierarchies being recreated, but only a single item will be found in the compendium.
- Right click and export to compendium: 
   - nothing is exported
   - nothing appears in the logs
- Drag and drop a folder to compendium:
   - Folders are created normally and logged
   - For each item appearing in the world's folders, a "Created Item with id..." entry appears, with all items reporting the same id.
    ![image](https://github.com/SobranDM/foundryvtt-wwn/assets/97160/2d31c927-c609-4e99-8550-28911590838f)
   - The compendium folders will contain just a single item.
    ![image](https://github.com/SobranDM/foundryvtt-wwn/assets/97160/b2ed7cef-d0b5-465a-a53c-d8ab87385248)

**Comment by tuirgin** [comment]
I created a new world and a new compendium module for testing this behavior. No other modules were enabled.
![image](https://github.com/SobranDM/foundryvtt-wwn/assets/97160/86cea07e-2a25-465c-a3b2-a93b391142d4)

**Comment by SobranDM** [comment]
Well that doesn't seem to be desired behavior. I'll do some checking, as this is a potential showstopper.

**Comment by tuirgin** [comment]
I should have clarified that this behavior specifically impacts *item* compendiums but not actors, journal entries, roll tables, or macros.

**Comment by tuirgin** [comment]
This no longer seems to be an issue as of WWN 1.4.5 on FVTT 12.327. I was able to create a new world and import/export my items from/to compendiums without any obvious issues.
